-- NV Supabase database setup
-- Run this in Supabase SQL Editor.
-- Then create a Storage bucket named: product-images
-- Set the bucket to PUBLIC for this starter, or replace image handling with signed URLs for private storage.

create extension if not exists "pgcrypto";

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text default '',
  price numeric(12,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  sizes text default 'S,M,L,XL,XXL',
  image_url text default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
using (active = true);

drop policy if exists "Users can insert their order items" on public.order_items;
create policy "Users can insert their order items"
on public.order_items for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can view their order items" on public.order_items;
create policy "Users can view their order items"
on public.order_items for select
to authenticated
using (auth.uid() = user_id);

-- Storage:
-- Create a PUBLIC bucket named product-images in Supabase Storage.
-- The browser admin upload is protected by the products table policy below only if
-- you add a real admin role/claim. For a stronger production setup, use Supabase
-- custom claims/RBAC and storage policies. This starter additionally checks ADMIN_EMAIL
-- in the browser for the admin UI, but production authorization MUST be server/RLS based.

-- Optional seed products:
insert into public.products (name,category,description,price,stock,sizes,image_url,active)
select * from (values
 ('Royal Silk Kurta','Kurta','Elegant silk kurta for weddings and festive occasions.',2499,20,'M,L,XL,XXL','',true),
 ('Classic Nehru Jacket','Nehru Jacket','Refined waistcoat-style jacket for ceremonies and celebrations.',1899,15,'M,L,XL,XXL','',true),
 ('Festive Kurta Pajama','Kurta Pajama','Comfortable traditional set for festive occasions.',1599,30,'S,M,L,XL,XXL','',true)
) as v(name,category,description,price,stock,sizes,image_url,active)
where not exists (select 1 from public.products);
